"""Initial migration

Revision ID: 0876859ea891
Revises: 
Create Date: 2025-11-24 16:47:31.237997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0876859ea891'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_turnos_cliente_id'), table_name='turnos')
    op.drop_index(op.f('ix_turnos_estado'), table_name='turnos')
    op.drop_index(op.f('ix_turnos_fecha_hora'), table_name='turnos')
    op.drop_index(op.f('ix_turnos_id'), table_name='turnos')
    op.drop_index(op.f('ix_turnos_proveedor_id'), table_name='turnos')
    op.drop_index(op.f('ix_turnos_servicio_id'), table_name='turnos')
    op.drop_table('turnos')
    op.add_column('servicios', sa.Column('categoria', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_servicios_categoria'), 'servicios', ['categoria'], unique=False)
    op.drop_column('servicios', 'duracion_minutos')
    op.drop_column('servicios', 'precio')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servicios', sa.Column('precio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('servicios', sa.Column('duracion_minutos', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_servicios_categoria'), table_name='servicios')
    op.drop_column('servicios', 'categoria')
    op.create_table('turnos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('proveedor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('servicio_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fecha_hora', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('duracion_minutos', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('estado', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('precio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('notas_cliente', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('notas_proveedor', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('motivo_cancelacion', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('fecha_cancelacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name=op.f('turnos_cliente_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], name=op.f('turnos_proveedor_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.id'], name=op.f('turnos_servicio_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('turnos_pkey'))
    )
    op.create_index(op.f('ix_turnos_servicio_id'), 'turnos', ['servicio_id'], unique=False)
    op.create_index(op.f('ix_turnos_proveedor_id'), 'turnos', ['proveedor_id'], unique=False)
    op.create_index(op.f('ix_turnos_id'), 'turnos', ['id'], unique=False)
    op.create_index(op.f('ix_turnos_fecha_hora'), 'turnos', ['fecha_hora'], unique=False)
    op.create_index(op.f('ix_turnos_estado'), 'turnos', ['estado'], unique=False)
    op.create_index(op.f('ix_turnos_cliente_id'), 'turnos', ['cliente_id'], unique=False)
    # ### end Alembic commands ###
