"""Add Pagos to Reserva

Revision ID: 1cbe9d12746f
Revises: 0876859ea891
Create Date: 2025-11-25 14:37:22.907556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cbe9d12746f'
down_revision: Union[str, Sequence[str], None] = '0876859ea891'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservas', sa.Column('pago_confirmado', sa.Boolean(), nullable=True))
    op.add_column('reservas', sa.Column('notas_pago', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservas', 'notas_pago')
    op.drop_column('reservas', 'pago_confirmado')
    # ### end Alembic commands ###
